name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  open_meteo_api:
    path: ../open_meteo_api


dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^4.0.0+1
