name: weather_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.14
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
