name: local_storage_todos_api
description: A Flutter implementation of the TodosApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  meta: 
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
